# Generated by Django 5.2.10 on 2026-01-30 04:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=50, verbose_name="Institution"),
                ),
                (
                    "course",
                    models.CharField(max_length=50, verbose_name="Course Title"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "end_date",
                    models.DateField(auto_now_add=True, verbose_name="End date"),
                ),
                ("remarks", models.TextField(verbose_name="Remarks")),
            ],
        ),
        migrations.CreateModel(
            name="Interests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("tags", models.CharField(max_length=50, verbose_name="Tags")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "mobile",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Mobile"
                    ),
                ),
                ("bio", models.TextField(verbose_name="")),
                ("linkedIn", models.URLField(verbose_name="LinkedIn")),
                ("github", models.URLField(verbose_name="Github")),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("details", models.TextField(verbose_name="Details")),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.CharField(max_length=50, verbose_name="Skills")),
                (
                    "proficiency",
                    models.CharField(max_length=50, verbose_name="Proficiency"),
                ),
                ("tags", models.CharField(max_length=50, verbose_name="Tags")),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=50, verbose_name="Company"),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("remarks", models.TextField(verbose_name="Remarks")),
            ],
        ),
    ]
