# Generated by Django 5.2.10 on 2026-01-30 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="type",
            new_name="typeof",
        ),
        migrations.AddField(
            model_name="education",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interests",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projects",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skills",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workexperience",
            name="profile",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.profile",
            ),
            preserve_default=False,
        ),
    ]
