# Generated by Django 5.2.10 on 2026-01-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_type_projects_typeof_education_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(verbose_name="Bio"),
        ),
    ]
