# Generated by Django 5.2.10 on 2026-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_date",
            field=models.DateField(verbose_name="End date"),
        ),
    ]
